var A="woolcock_windform_in_lab_";
var list={
    "Visit 1 Day 1 3.30PM":[
        'woolcock_windform_in_lab_v1d1ae_vas',
        'woolcock_windform_in_lab_v1d1ae_2back',
        'woolcock_windform_in_lab_v1d1ae_tol',
    ],
    "Visit 1 Day 1 7.30PM":[
        'woolcock_windform_in_lab_v1d1al_vas',
        'woolcock_windform_in_lab_v1d1al_2back',
        'woolcock_windform_in_lab_v1d1al_tol',
    ],
    "Visit 1 Day 2 7.30AM":[
        'woolcock_windform_in_lab_v1d2me_vas',
        'woolcock_windform_in_lab_v1d2me_2back',
        'woolcock_windform_in_lab_v1d2me_tol',
    ],
    "Visit 1 Day 2 11.30AM":[
        'woolcock_windform_in_lab_v1d2ml_vas',
        'woolcock_windform_in_lab_v1d2ml_2back',
        'woolcock_windform_in_lab_v1d2ml_tol',
    ],
    "Visit 1 Day 2 3.30PM":[
        'woolcock_windform_in_lab_v1d2ae_vas',
        'woolcock_windform_in_lab_v1d2ae_2back',
        'woolcock_windform_in_lab_v1d2ae_tol',
    ],
    "Visit 1 Day 2 7.30PM":[
        'woolcock_windform_in_lab_v1d2al_vas',
        'woolcock_windform_in_lab_v1d2al_2back',
        'woolcock_windform_in_lab_v1d2al_tol',
    ],
    "Visit 1 Day 3 7.30AM":[
        'woolcock_windform_in_lab_v1d3me_vas',
        'woolcock_windform_in_lab_v1d3me_2back',
        'woolcock_windform_in_lab_v1d3me_tol',
    ],
    "Visit 1 Day 3 11.30AM":[
        'woolcock_windform_in_lab_v1d3ml_vas',
        'woolcock_windform_in_lab_v1d3ml_2back',
        'woolcock_windform_in_lab_v1d3ml_tol',
    ],
    "Visit 1 Day 3 3.30PM":[
        'woolcock_windform_in_lab_v1d3ae_vas',
        'woolcock_windform_in_lab_v1d3ae_2back',
        'woolcock_windform_in_lab_v1d3ae_tol',
    ],
    "Visit 1 Day 3 7.30PM":[
        'woolcock_windform_in_lab_v1d3al_vas',
        'woolcock_windform_in_lab_v1d3al_2back',
        'woolcock_windform_in_lab_v1d3al_tol',
    ],
    "Visit 1 Day 4 7.30AM":[
        'woolcock_windform_in_lab_v1d4me_vas',
        'woolcock_windform_in_lab_v1d4me_2back',
        'woolcock_windform_in_lab_v1d4me_tol',
        'woolcock_windform_in_lab_v1d4me_insomnia',
        'woolcock_windform_in_lab_v1d4me_kessler',
        'woolcock_windform_in_lab_v1d4me_staxi',
        'woolcock_windform_in_lab_v1d4me_wewb',
        'woolcock_windform_in_lab_v1d4me_dass',
        'woolcock_windform_in_lab_v1d4me_noise',
    ],
    "Visit 2 Day 1 3.30PM":[
        'woolcock_windform_in_lab_v2d1ae_vas',
        'woolcock_windform_in_lab_v2d1ae_2back',
        'woolcock_windform_in_lab_v2d1ae_tol',
    ],
    "Visit 2 Day 1 7.30PM":[
        'woolcock_windform_in_lab_v2d1al_vas',
        'woolcock_windform_in_lab_v2d1al_2back',
        'woolcock_windform_in_lab_v2d1al_tol',
    ],
    "Visit 2 Day 2 7.30AM":[
        'woolcock_windform_in_lab_v2d2me_vas',
        'woolcock_windform_in_lab_v2d2me_2back',
        'woolcock_windform_in_lab_v2d2me_tol',
    ],
    "Visit 2 Day 2 11.30AM":[
        'woolcock_windform_in_lab_v2d2ml_vas',
        'woolcock_windform_in_lab_v2d2ml_2back',
        'woolcock_windform_in_lab_v2d2ml_tol',
    ],
    "Visit 2 Day 2 3.30PM":[
        'woolcock_windform_in_lab_v2d2ae_vas',
        'woolcock_windform_in_lab_v2d2ae_2back',
        'woolcock_windform_in_lab_v2d2ae_tol',
    ],
    "Visit 2 Day 2 7.30PM":[
        'woolcock_windform_in_lab_v2d2al_vas',
        'woolcock_windform_in_lab_v2d2al_2back',
        'woolcock_windform_in_lab_v2d2al_tol',
    ],
    "Visit 2 Day 3 7.30AM":[
        'woolcock_windform_in_lab_v2d3me_vas',
        'woolcock_windform_in_lab_v2d3me_2back',
        'woolcock_windform_in_lab_v2d3me_tol',
    ],
    "Visit 2 Day 3 11.30AM":[
        'woolcock_windform_in_lab_v2d3ml_vas',
        'woolcock_windform_in_lab_v2d3ml_2back',
        'woolcock_windform_in_lab_v2d3ml_tol',
    ],
    "Visit 2 Day 3 3.30PM":[
        'woolcock_windform_in_lab_v2d3ae_vas',
        'woolcock_windform_in_lab_v2d3ae_2back',
        'woolcock_windform_in_lab_v2d3ae_tol',
    ],
    "Visit 2 Day 3 7.30PM":[
        'woolcock_windform_in_lab_v2d3al_vas',
        'woolcock_windform_in_lab_v2d3al_2back',
        'woolcock_windform_in_lab_v2d3al_tol',
    ],
    "Visit 2 Day 4 7.30AM":[
        'woolcock_windform_in_lab_v2d4me_vas',
        'woolcock_windform_in_lab_v2d4me_2back',
        'woolcock_windform_in_lab_v2d4me_tol',
        'woolcock_windform_in_lab_v2d4me_insomnia',
        'woolcock_windform_in_lab_v2d4me_kessler',
        'woolcock_windform_in_lab_v2d4me_staxi',
        'woolcock_windform_in_lab_v2d4me_wewb',
        'woolcock_windform_in_lab_v2d4me_dass',
        'woolcock_windform_in_lab_v2d4me_noise',
    ],
    "Visit 3 Day 1 3.30PM":[
        'woolcock_windform_in_lab_v3d1ae_vas',
        'woolcock_windform_in_lab_v3d1ae_2back',
        'woolcock_windform_in_lab_v3d1ae_tol',
    ],
    "Visit 3 Day 1 7.30PM":[
        'woolcock_windform_in_lab_v3d1al_vas',
        'woolcock_windform_in_lab_v3d1al_2back',
        'woolcock_windform_in_lab_v3d1al_tol',
    ],
    "Visit 3 Day 2 7.30AM":[
        'woolcock_windform_in_lab_v3d2me_vas',
        'woolcock_windform_in_lab_v3d2me_2back',
        'woolcock_windform_in_lab_v3d2me_tol',
    ],
    "Visit 3 Day 2 11.30AM":[
        'woolcock_windform_in_lab_v3d2ml_vas',
        'woolcock_windform_in_lab_v3d2ml_2back',
        'woolcock_windform_in_lab_v3d2ml_tol',
    ],
    "Visit 3 Day 2 3.30PM":[
        'woolcock_windform_in_lab_v3d2ae_vas',
        'woolcock_windform_in_lab_v3d2ae_2back',
        'woolcock_windform_in_lab_v3d2ae_tol',
    ],
    "Visit 3 Day 2 7.30PM":[
        'woolcock_windform_in_lab_v3d2al_vas',
        'woolcock_windform_in_lab_v3d2al_2back',
        'woolcock_windform_in_lab_v3d2al_tol',
    ],
    "Visit 3 Day 3 7.30AM":[
        'woolcock_windform_in_lab_v3d3me_vas',
        'woolcock_windform_in_lab_v3d3me_2back',
        'woolcock_windform_in_lab_v3d3me_tol',
    ],
    "Visit 3 Day 3 11.30AM":[
        'woolcock_windform_in_lab_v3d3ml_vas',
        'woolcock_windform_in_lab_v3d3ml_2back',
        'woolcock_windform_in_lab_v3d3ml_tol',
    ],
    "Visit 3 Day 3 3.30PM":[
        'woolcock_windform_in_lab_v3d3ae_vas',
        'woolcock_windform_in_lab_v3d3ae_2back',
        'woolcock_windform_in_lab_v3d3ae_tol',
    ],
    "Visit 3 Day 3 7.30PM":[
        'woolcock_windform_in_lab_v3d3al_vas',
        'woolcock_windform_in_lab_v3d3al_2back',
        'woolcock_windform_in_lab_v3d3al_tol',
    ],
    "Visit 3 Day 4 7.30AM":[
        'woolcock_windform_in_lab_v3d4me_vas',
        'woolcock_windform_in_lab_v3d4me_2back',
        'woolcock_windform_in_lab_v3d4me_tol',
        'woolcock_windform_in_lab_v3d4me_insomnia',
        'woolcock_windform_in_lab_v3d4me_kessler',
        'woolcock_windform_in_lab_v3d4me_staxi',
        'woolcock_windform_in_lab_v3d4me_wewb',
        'woolcock_windform_in_lab_v3d4me_dass',
        'woolcock_windform_in_lab_v3d4me_noise',
    ],
};
